<?php

namespace Database\Seeders;

use App\Models\data_guru;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DataGuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataGuru = [
            [
                'nip' => '1000',
                'nama_guru'=> 'NASRULLAH NURUL R.,S.Pd,M.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2000',
                'nama_guru'=> 'Dr. SAMSORI, S.Pd, M.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3000',
                'nama_guru'=> 'SRI UMI MARDIASIH, S.Pd, M.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4000',
                'nama_guru'=> 'ENDRIYANTO TRILAKSONO, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5000',
                'nama_guru'=> 'M. ABU DARIN, S.Ag',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6000',
                'nama_guru'=> 'SITI SUNDARI, S.Pd, M.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '7000',
                'nama_guru'=> 'WIWIN MUSTIKAYANA, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '8000',
                'nama_guru'=> 'DIAH RETNO WULAN T, S.Pd, M.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '9000',
                'nama_guru'=> 'ROSDINA HAEDAR, S.Pd. M.PdI',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1100',
                'nama_guru'=> 'MOCH. NAFSIR, S.PdI',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1200',
                'nama_guru'=> 'EVVI TRISNA MARTDIANY, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1300',
                'nama_guru'=> 'ENUNG SARIFAH, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1400',
                'nama_guru'=> 'DEWI NURYAWATI, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1500',
                'nama_guru'=> 'DUDI HARYADI, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1600',
                'nama_guru'=> 'AI SUHARTINI, SE',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1700',
                'nama_guru'=> 'EVVA YAKVIAWATI,S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1800',
                'nama_guru'=> 'IDA LESTARI, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '1900',
                'nama_guru'=> 'SITI DARAJAT, S.Pd.,Gr',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2100',
                'nama_guru'=> 'AGUS HERYANA,S.Pd.,Gr',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2200',
                'nama_guru'=> 'AZIZI ANI NUR MELAWATI, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2300',
                'nama_guru'=> 'JENNY NUR APRIYANTI, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2400',
                'nama_guru'=> 'INDRA BATARA, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2500',
                'nama_guru'=> 'WARDIATI, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2600',
                'nama_guru'=> 'IKA NOVITASARI, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2700',
                'nama_guru'=> 'FITRAYANTI FEBRIA C., S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2800',
                'nama_guru'=> 'ATIEK OCTARIA P. S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '2900',
                'nama_guru'=> 'RAKAI META PUSPARINI, S.Pt',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3100',
                'nama_guru'=> 'SUKANDA WIGUNA, S.T.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3200',
                'nama_guru'=> 'RUDY, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3300',
                'nama_guru'=> 'LISTIA MEILIANA SARI, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3400',
                'nama_guru'=> 'SALIMAN, S.Ag',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3500',
                'nama_guru'=> 'MUTIARA ZAHRA, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3600',
                'nama_guru'=> 'EUIS YULISTRIA, S.Kom.I',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3700',
                'nama_guru'=> 'ANNISA SABILLA',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3800',
                'nama_guru'=> 'ELIZA PUSPA, S.Pd., M.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '3900',
                'nama_guru'=> 'LENI MARLIATI, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4100',
                'nama_guru'=> 'RIZKY FAUZI ACHMAN, S.Kom.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4200',
                'nama_guru'=> 'MUHAMAD YUSRIL NUGRAHA',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4300',
                'nama_guru'=> 'MAYANG PERMATA SARI, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4400',
                'nama_guru'=> 'FAUZIAH NUR ALIFAH, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4500',
                'nama_guru'=> 'SENI JULIA TERESNA AYUNDA, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4600',
                'nama_guru'=> 'HIKMAL SETIAWAN, S.Pd.,M.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4700',
                'nama_guru'=> 'MINATI ARFAH, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4800',
                'nama_guru'=> 'FARIDA TYAS, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '4900',
                'nama_guru'=> 'PUTRI NURJANAH MUSLIMAH, S.Pd.,Gr',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5100',
                'nama_guru'=> 'DIAN HARDIANA, S.Kom.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5200',
                'nama_guru'=> 'NESA SEPTIANA, S.Psi.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5400',
                'nama_guru'=> 'FAHRY FIRMANSAH ABDUL ROHMAN',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5600',
                'nama_guru'=> 'SUCI SULASTRI, S.Kom., MOS., MTCNA',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5700',
                'nama_guru'=> 'RENI MULYANI,S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5800',
                'nama_guru'=> 'RIFKI AHMAD, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '5900',
                'nama_guru'=> 'EDI YUSMAN, S.E., M.M.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6100',
                'nama_guru'=> 'WIJAYA MUSTOPA, S.Ip',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6200',
                'nama_guru'=> 'MUHAMMAD AKBAR, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6300',
                'nama_guru'=> 'DIMAS YONATHAN, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6400',
                'nama_guru'=> 'YUDI KURNIA SOLIHIN, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6500',
                'nama_guru'=> 'INDAH NURSYAIFA D., S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6600',
                'nama_guru'=> 'TETI SURYATI, S.Pd.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6700',
                'nama_guru'=> 'Dennis Aji Muhammad Jabar, S.Kom',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6800',
                'nama_guru'=> 'Ria Pangestu, S.Pd',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Perempuan',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
            [
                'nip' => '6900',
                'nama_guru'=> 'DENIS AJI MUHAMAD JABAR, S.Kom.',
                'tempat_lahir'=> 'Bandung',
                'tanggal_lahir'=> '1990-01-01',
                'jenis_kelamin'=> 'Laki-laki',
                'agama'=> 'Islam',
                'no_hp'=> '08123123123',
                'provinsi'=> 'Jawa Barat',
                'kota'=> 'Cimahi',
                'desa'=> 'Cibeber',
                'rt'=> '01',
                'rw'=> '01',
                'alamat'=> 'jl. Ibu gandirah',
                'foto_guru' => ''
            ],
        ];

        foreach ($dataGuru as $key => $val){
            data_guru::create($val);
        }
    }
}
