<?php

namespace Database\Seeders;

use App\Models\data_jadwal;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DataJadwalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataJadwal = [
            [
                'hari' => 'Senin',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '09:20',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '19',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '19:20',
                'waktu_keluar' => '12:05',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '40',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '12:05',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '21',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '26',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '23',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '11:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '20',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '29',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '10:14',
                'waktu_keluar' => '13:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '42',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '13:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '16',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '40',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '10:15',
                'waktu_keluar' => '12:30',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '32',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '13:00',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '23',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '08:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '21',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '08:00',
                'waktu_keluar' => '09:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '12',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '1',
                'nama_kelas' => 'PPLG 1',
                'pengampu_id' => '40',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '09:20',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '30',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '19:20',
                'waktu_keluar' => '12:05',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '16',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '12:05',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '49',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '25',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '22',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '11:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '24',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '30',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '10:14',
                'waktu_keluar' => '13:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '19',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '13:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '24',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '13',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '10:15',
                'waktu_keluar' => '12:30',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '19',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '13:00',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '47',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '08:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '12',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '08:00',
                'waktu_keluar' => '09:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '30',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '4',
                'nama_kelas' => 'PM 1',
                'pengampu_id' => '18',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '09:20',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '7',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '19:20',
                'waktu_keluar' => '12:05',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '4',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '12:05',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '48',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '15',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '24',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '11:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '5',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '35',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '10:14',
                'waktu_keluar' => '13:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '43',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '13:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '19',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '45',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '10:15',
                'waktu_keluar' => '12:30',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '24',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '13:00',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '35',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '08:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '35',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '08:00',
                'waktu_keluar' => '09:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '31',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '7',
                'nama_kelas' => 'MPLB 1',
                'pengampu_id' => '16',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '09:20',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '29',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '19:20',
                'waktu_keluar' => '12:05',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '23',
            ],
            [
                'hari' => 'Senin',
                'waktu_masuk' => '12:05',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '8',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '16',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '4',
            ],
            [
                'hari' => 'Selasa',
                'waktu_masuk' => '11:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '25',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '3',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '10:14',
                'waktu_keluar' => '13:45',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '23',
            ],
            [
                'hari' => 'Rabu',
                'waktu_masuk' => '13:45',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '29',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '10:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '19',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '10:15',
                'waktu_keluar' => '12:30',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '1',
            ],
            [
                'hari' => 'Kamis',
                'waktu_masuk' => '13:00',
                'waktu_keluar' => '15:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '48',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '08:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '15',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '08:00',
                'waktu_keluar' => '09:00',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '3',
            ],
            [
                'hari' => 'Jumat',
                'waktu_masuk' => '09:15',
                'waktu_keluar' => '11:15',
                'tingkat_id' => '1',
                'nama_tingkat' => 'X',
                'kelas_id' => '10',
                'nama_kelas' => 'AKL 1',
                'pengampu_id' => '5',
            ],
        ];

        foreach($dataJadwal as $key => $val){
            data_jadwal::create($val);
        }
    }
}
